# Config file for CelebA dataset (200k)

output_dir: '/home/k4agrawal/Efficient_Image_Reconstruction/StyleGAN.pytorch/checkpoints/ch1'
structure: 'linear'
device_id: ('0')
checkpoint_factor: 4
inpainting: True
feedback_factor: 4
dataset:
  img_dir: '/home/k4agrawal/Efficient_Image_Reconstruction/StyleGAN.pytorch/ffhq'
  folder: True
  resolution: 128
sched:
  epochs: [8,16,32,32,64,64]
