output_dir: '/data/hzh/checkpoints/StyleGAN.pytorch/ckp_cari2'
structure: 'linear'
device_id: ('3')
checkpoint_factor: 4
feedback_factor: 4
model:
  gen:
    mapping_layers: 8
    # Negative numbers represent no truncation layers
    truncation_psi: -1.
dataset:
  img_dir: '/home/hzh/data/Cari2-128'
  folder: False
  resolution: 128
sched:
  epochs: [8,16,32,32,64,64]
