output_dir: '/data/hzh/checkpoints/StyleGAN.pytorch/ckp_cari2_logistic'
structure: 'linear'
device_id: ('2')
checkpoint_factor: 4
feedback_factor: 4
loss: 'logistic'
model:
  gen:
    mapping_layers: 8
dataset:
  img_dir: '/home/hzh/data/Cari2-128'
  folder: False
  resolution: 128
sched:
  epochs: [8,16,32,32,64,64]
