# Config file for CelebA dataset (200k)

output_dir: '/data/hzh/checkpoints/StyleGAN.pytorch/ckp_ffhq_1'
structure: 'linear'
device_id: ('3')
checkpoint_factor: 4
feedback_factor: 4
dataset:
  img_dir: '/home/hzh/data/FFHQ'
  folder: True
  resolution: 1024
model:
  gen:
    mapping_layers: 8
    # Negative numbers represent no truncation layers
    truncation_psi: -1.
sched:
  epochs: [8,16,32,32,64,64]
